#!/usr/bin/env bash
#
# Regenerate the Homebrew formula for astrobin-csv in the samf/homebrew-samf
# tap from the artifacts GoReleaser just built, then commit and push it.
#
# Expects to run after `goreleaser release`, with dist/checksums.txt present.
#
# Environment:
#   GITHUB_REF_NAME            the pushed tag, e.g. v1.2.3 (set by Actions)
#   HOMEBREW_TAP_GITHUB_TOKEN  token with write access to the tap repo
#   DRY_RUN=1                  print the formula instead of pushing it
#
set -euo pipefail

APP="astrobin-csv"
CLASS="AstrobinCsv"
DESC="Generate an AstroBin acquisition CSV from NINA FITS/XISF light frames"
LICENSE="MIT"
REPO_OWNER="samf"
TAP_REPO="homebrew-samf"
CHECKSUMS="${CHECKSUMS:-dist/checksums.txt}"

TAG="${GITHUB_REF_NAME:?GITHUB_REF_NAME (the tag) must be set}"
VERSION="${TAG#v}"
HOMEPAGE="https://github.com/${REPO_OWNER}/${APP}"
URL_BASE="https://github.com/${REPO_OWNER}/${APP}/releases/download/${TAG}"

# sha_for prints the sha256 of the named archive from the checksums file.
sha_for() {
  local fn="$1" sha
  sha="$(awk -v f="$fn" '$2 == f { print $1 }' "$CHECKSUMS")"
  if [ -z "$sha" ]; then
    echo "error: no checksum for $fn in $CHECKSUMS" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

archive() { printf '%s_%s_%s_%s.tar.gz' "$APP" "$VERSION" "$1" "$2"; }

darwin_amd64="$(archive darwin amd64)"
darwin_arm64="$(archive darwin arm64)"
linux_amd64="$(archive linux amd64)"
linux_arm64="$(archive linux arm64)"

# Resolve all checksums up front so a missing one aborts (set -e catches the
# failed assignment) rather than silently emitting an empty sha256.
sha_darwin_amd64="$(sha_for "$darwin_amd64")"
sha_darwin_arm64="$(sha_for "$darwin_arm64")"
sha_linux_amd64="$(sha_for "$linux_amd64")"
sha_linux_arm64="$(sha_for "$linux_arm64")"

read -r -d '' FORMULA <<EOF || true
# typed: false
# frozen_string_literal: true

# This file is generated by the astrobin-csv release workflow. DO NOT EDIT.
class ${CLASS} < Formula
  desc "${DESC}"
  homepage "${HOMEPAGE}"
  version "${VERSION}"
  license "${LICENSE}"

  on_macos do
    on_intel do
      url "${URL_BASE}/${darwin_amd64}"
      sha256 "${sha_darwin_amd64}"
    end
    on_arm do
      url "${URL_BASE}/${darwin_arm64}"
      sha256 "${sha_darwin_arm64}"
    end
  end

  on_linux do
    on_intel do
      url "${URL_BASE}/${linux_amd64}"
      sha256 "${sha_linux_amd64}"
    end
    on_arm do
      url "${URL_BASE}/${linux_arm64}"
      sha256 "${sha_linux_arm64}"
    end
  end

  def install
    bin.install "${APP}"
  end

  test do
    system "#{bin}/${APP}", "--help"
  end
end
EOF

if [ "${DRY_RUN:-}" = "1" ]; then
  printf '%s\n' "$FORMULA"
  exit 0
fi

: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN must be set}"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/${REPO_OWNER}/${TAP_REPO}.git" \
  "$workdir/tap"

mkdir -p "$workdir/tap/Formula"
printf '%s\n' "$FORMULA" > "$workdir/tap/Formula/${APP}.rb"

cd "$workdir/tap"
git config user.name "goreleaser-bot"
git config user.email "goreleaser@users.noreply.github.com"
git add "Formula/${APP}.rb"

# --cached so a brand-new (untracked) formula on the first release still counts
# as a change to commit.
if git diff --cached --quiet; then
  echo "Formula already up to date for ${TAG}; nothing to commit."
  exit 0
fi

git commit -m "${APP} ${VERSION}"
git push origin HEAD
echo "Pushed ${APP} ${VERSION} formula to ${REPO_OWNER}/${TAP_REPO}."
